project_name: daad

release:
  github:
    owner: daadLang
    name: daad

builds:
  - id: daad
    main: ./
    binary: daad
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
    env:
      - CGO_ENABLED=0
    dir: .
    ldflags:
      - -s -w
      - -X github.com/daadLang/daad/internals/pkg.Version={{.Version}}
      - -X github.com/daadLang/daad/internals/pkg.GitCommit={{.ShortCommit}}
      - -X github.com/daadLang/daad/internals/pkg.BuildDate={{.Date}}
      - -X github.com/daadLang/daad/internals/pkg.GoVersion=1.25

archives:
  - id: daad-archive
    builds:
      - daad
    format_overrides:
      - goos: windows
        format: zip
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

nfpms:
  - id: linux-packages
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    builds:
      - daad
    section: default
    maintainer: "B-AJ-Amar <amarbouakaz91@gmail.com>, Ox03bb <alibouakaz91@gmail.com>"
    description: "Arabic programming language"
    license: Apache-2.0
    homepage: "https://github.com/daadLang/daad"


 
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

before:
  hooks:
    - go mod tidy
    - go test ./...